import os
import subprocess
import re
import requests
from dotenv import load_dotenv
from quality import BlogQualityAnalyzer

def run_git_command(args, cwd=None):
    result = subprocess.run(
        ["git"] + args,
        cwd=cwd,
        capture_output=True,
        text=True,
        shell=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"Git command failed: git {' '.join(args)}\nError: {result.stderr.strip()}")
    return result.stdout.strip()

def create_pull_request_for_blog(filename, commit_message=None):
    workspace_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    load_dotenv(os.path.join(workspace_dir, ".env"))
    
    github_token = os.getenv("GITHUB_TOKEN")
    owner = os.getenv("GITHUB_OWNER", "chadasaiteja")
    repo = os.getenv("GITHUB_REPOSITORY", "chadasaiteja.github.io")
    
    if not github_token:
        return False, None, "GITHUB_TOKEN is missing in .env file. Please add a GitHub Personal Access Token to publish."
        
    fpath = os.path.join(workspace_dir, "_posts", filename)
    if not os.path.exists(fpath):
        return False, None, f"Article draft file not found: _posts/{filename}"

    analyzer = BlogQualityAnalyzer(fpath)
    try:
        analyzer.analyze()
        score = analyzer.get_total_score()
    except Exception as e:
        return False, None, f"Failed running quality checks before publish: {e}"
        
    slug_match = re.search(r'\d{4}-\d{2}-\d{2}-(.*)\.md$', filename)
    slug = slug_match.group(1) if slug_match else "blog-post"
    branch_name = f"blog/add-{slug}"
    
    title = analyzer.frontmatter.get("title", slug.replace("-", " ").capitalize())
    if not commit_message:
        commit_message = f"Add blog: {title}"
        
    previous_branch = "main"
    
    try:
        try:
            previous_branch = run_git_command(["rev-parse", "--abbrev-ref", "HEAD"], cwd=workspace_dir)
        except Exception:
            pass
            
        print(f"Git: Current branch is {previous_branch}")
        remote_url = f"https://x-access-token:{github_token}@github.com/{owner}/{repo}.git"
        
        print(f"Git: Checking out new branch {branch_name}...")
        try:
            run_git_command(["checkout", "-b", branch_name], cwd=workspace_dir)
        except Exception:
            run_git_command(["checkout", branch_name], cwd=workspace_dir)
            
        print(f"Git: Staging file _posts/{filename}...")
        run_git_command(["add", f"_posts/{filename}"], cwd=workspace_dir)
        
        print(f"Git: Committing changes...")
        try:
            run_git_command(["commit", "-m", commit_message], cwd=workspace_dir)
        except Exception as ce:
            if "nothing to commit" in str(ce).lower():
                print("Git: Content already committed.")
            else:
                raise ce
                
        print(f"Git: Pushing branch {branch_name} to remote...")
        run_git_command(["push", remote_url, f"{branch_name}:{branch_name}", "--force"], cwd=workspace_dir)
        
        print(f"Git: Restoring previous branch {previous_branch}...")
        run_git_command(["checkout", previous_branch], cwd=workspace_dir)
        
    except Exception as git_err:
        try:
            run_git_command(["checkout", previous_branch], cwd=workspace_dir)
        except:
            pass
        return False, None, f"Git local automation error: {git_err}"

    print("GitHub API: Creating Pull Request...")
    pr_headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json",
        "Content-Type": "application/json"
    }
    
    pr_body_desc = (
        f"## Blog Publishing Automation\n\n"
        f"**Title:** {title}\n"
        f"**Slug:** {slug}\n"
        f"**Quality Score:** {score}/100\n\n"
        f"### Summary\n"
        f"This is an automated publication generated by the Blog Creator AI system.\n\n"
        f"### Verification Checks\n"
        f"- [x] Markdown generated with metadata frontmatter\n"
        f"- [x] Local emulated layouts previewed\n"
        f"- [x] Quality checks ran (Score: {score}/100)\n"
        f"- [x] Git branch created & committed\n"
    )
    
    pr_payload = {
        "title": commit_message,
        "head": branch_name,
        "base": "main",
        "body": pr_body_desc
    }
    
    api_url = f"https://api.github.com/repos/{owner}/{repo}/pulls"
    
    try:
        response = requests.post(api_url, headers=pr_headers, json=pr_payload, timeout=20)
        
        if response.status_code == 201:
            pr_data = response.json()
            pr_url = pr_data.get("html_url")
            print(f"GitHub API: Pull Request successfully created! URL: {pr_url}")
            return True, pr_url, None
        else:
            if "A pull request already exists" in response.text:
                list_url = f"https://api.github.com/repos/{owner}/{repo}/pulls?head={owner}:{branch_name}"
                list_resp = requests.get(list_url, headers=pr_headers, timeout=10)
                if list_resp.status_code == 200 and len(list_resp.json()) > 0:
                    pr_url = list_resp.json()[0].get("html_url")
                    return True, pr_url, None
            return False, None, f"GitHub API error ({response.status_code}): {response.text}"
            
    except Exception as api_err:
        return False, None, f"GitHub API request failed: {api_err}"
